version: '3'

services:
    nginx:
        image: nginx
        hostname: nginx
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always

    api:
        container_name: api
        hostname: api
        build: .
        ports:
            - 3000:3000
        restart: always
        depends_on:
            - nginx
            - elasticsearch

    mongo:
        container_name: mongo
        hostname: mongo
        image: mongo
        ports:
            - 27017:27017
        restart: always

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
        hostname: elasticsearch
        container_name: elasticsearch
        ports:
            - 9200:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.1
        hostname: kibana
        container_name: kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
